"""Copyright 2026 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Smoke test that every Phase 4 verb is reachable + has working --help.
"""
from __future__ import annotations

import os
import subprocess
import sys


def _cde(*args, env=None) -> subprocess.CompletedProcess:
  return subprocess.run(
      [sys.executable, "-m", "cde", *args],
      capture_output=True, text=True, check=False, env=env,
  )


def test_help_lists_all_verbs():
  result = _cde("--help")
  assert result.returncode == 0, result.stderr
  for verb in (
      "init", "build", "run", "logs", "shell", "reap",
      "watch", "sync", "server",
      "history", "prune", "delete", "annotate", "hypothesize", "tag", "untag",
      "compare", "lineage", "defaults", "profile", "status",
  ):
    assert verb in result.stdout, f"verb {verb!r} missing from --help"


def test_logs_replica_accepts_name():
  """Gap 2: --replica accepts a name (e.g. -r worker, -r pathways-head),
  not just an integer index. Smoke-test by parsing --help text."""
  result = _cde("logs", "--help")
  assert result.returncode == 0, result.stderr
  assert "named replicatedJob" in result.stdout
  # Argparse may wrap the help text across lines; check for fragments.
  assert "worker" in result.stdout
  assert "pathways-head" in result.stdout


def test_each_verb_has_help():
  verbs = [
      ["watch"],
      ["sync"],
      ["server", "up"],
      ["server", "down"],
      ["server", "wait-ready"],
      ["logs"],
      ["shell"],
      ["reap"],
      ["history"],
      ["compare"],
      ["lineage"],
      ["annotate"],
      ["hypothesize"],
      ["tag"],
      ["untag"],
      ["defaults"],
      ["profile", "path"],
  ]
  for v in verbs:
    result = _cde(*v, "--help")
    assert result.returncode == 0, f"{' '.join(v)} --help: {result.stderr}"
    assert result.stdout, f"{' '.join(v)} --help produced no output"


def test_argcomplete_marker_present():
  """The PYTHON_ARGCOMPLETE_OK marker must be in the entry-point script
  so argcomplete picks it up. We check it via the source file directly
  since the installed entry-point is generated by setuptools."""
  import cde.cli
  src_path = cde.cli.__file__
  with open(src_path, "r", encoding="utf-8") as f:
    first_line = f.readline()
  assert "PYTHON_ARGCOMPLETE_OK" in first_line
