"""Smoke test that every Phase 4 verb is reachable + has working --help."""

from __future__ import annotations

import os
import subprocess
import sys


def _cde(*args, env=None) -> subprocess.CompletedProcess:
  return subprocess.run(
      [sys.executable, "-m", "cde", *args],
      capture_output=True, text=True, check=False, env=env,
  )


def test_help_lists_all_verbs():
  result = _cde("--help")
  assert result.returncode == 0, result.stderr
  for verb in (
      "init", "build", "run", "logs", "shell", "reap",
      "watch", "sync", "server",
      "history", "annotate", "hypothesize", "tag", "untag",
      "compare", "lineage", "defaults", "profile",
  ):
    assert verb in result.stdout, f"verb {verb!r} missing from --help"


def test_each_verb_has_help():
  verbs = [
      ["watch"],
      ["sync"],
      ["server", "up"],
      ["server", "down"],
      ["server", "wait-ready"],
      ["logs"],
      ["shell"],
      ["reap"],
      ["history"],
      ["compare"],
      ["lineage"],
      ["annotate"],
      ["hypothesize"],
      ["tag"],
      ["untag"],
      ["defaults"],
      ["profile", "path"],
  ]
  for v in verbs:
    result = _cde(*v, "--help")
    assert result.returncode == 0, f"{' '.join(v)} --help: {result.stderr}"
    assert result.stdout, f"{' '.join(v)} --help produced no output"


def test_argcomplete_marker_present():
  """The PYTHON_ARGCOMPLETE_OK marker must be in the entry-point script
  so argcomplete picks it up. We check it via the source file directly
  since the installed entry-point is generated by setuptools."""
  import cde.cli
  src_path = cde.cli.__file__
  with open(src_path, "r", encoding="utf-8") as f:
    first_line = f.readline()
  assert "PYTHON_ARGCOMPLETE_OK" in first_line
